---
- name: Start container Jenkins
  docker_container:
    name: jenkins
    image: "jenkins/jenkins:lts"
    privileged: yes
    ports:
     - "8080:8080"
     - "50000:50000"
    command: docker exec -it -u root jenkins bash -c "addgroup docker ; usermod -a -G docker jenkins"
#    restart_policy: always
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "/usr/bin/docker:/usr/bin/docker:ro"