---
- name: Start container Jenkins
  docker_container:
    name: jenkins
    hostname: ec2-18-233-153-17.compute-1.amazonaws.com
    image: "jenkins/jenkins:lts"
    network: host
    state: started
    restart_policy: always
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - "/jenkins_home:/var/jenkins_home"
