---
- name: Apt Update
  become: true
  apt:
    update-cache: yes
    
- name: Add key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  

- name: add repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: install Docker
  become: true  
  apt:
    update-cache: yes
    name:
    - python
    - python-pip
    - docker-ce
    - docker-ce-cli
    - containerd.io 

- name: install docker-py
  become: true
  pip:
    name: docker-py
    state: latest

- name: Start Docker
  become: true
  systemd:
    state: started
    name: docker

- name: add user to group docker
  become: true
  user:
    name: ubuntu
    groups: docker