- name: Apt Update
  become: true
  apt:
    update-cache: yes
    
- name: Add key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    
  apt:
    update-cache: yes
    name:
    - python
    - docker-ce
    - docker-ce-cli
    - containerd.io 

- name: Start Docker
  systemd:
    state: started
    name: docker
  user:
    name: ubuntu
    groups: docker
