---

- name: Cria ec2 key 
  ec2_key:
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    name: "{{ APP_KEY }}"
    region: "{{ AWS_REGION }}"
  register: ec2_my_key

- name: Salva key ec2
  copy: content="{{ ec2_my_key.key.private_key }}" dest="./{{ APP_KEY }}.pem" mode=0400
  when: ec2_my_key.changed

- name: Cria Security group
  ec2_group:
    name: "{{ SECURITY_GROUP }}"
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    description: fw
    vpc_id: vpc-d4348aae
    region: "{{ AWS_REGION }}"
    rules:
      - proto: tcp
        ports:
        - 22
        - 80
        - 443
        cidr_ip: 0.0.0.0/0

- name: Cria vm
  ec2_instance:
    key_name: "{{ APP_KEY }}"
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    instance_type: t2.micro
    image_id: ami-02b043c85d94864a9
    security_group: "{{ SECURITY_GROUP }}"
    tenancy: default
    name: "{{ VM_NAME }}"
    tags:
      Name: "{{ VM_NAME }}"
    wait: yes
    region: "{{ AWS_REGION }}"
    vpc_subnet_id: subnet-3c6b0312
    network:
      assign_public_ip: true