---
- name: Criando recursos EC2
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
       APP_KEY: ssh_key
       AWS_REGION: us-east-1a
       VM_NAME: instance_infra
       SECURITY_GROUP: security_group_infra
       AWS_ACCESS_KEY:
       AWS_SECRET_KEY:

  tasks:

    - name: Cria EC2_KEY
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        name: "{{ AAP_KEY }}"
        region: "{{ AWS_REGION }}"

    - name: Cria VPC
      ec2_vpc_net:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        name: My VPC
        cidr_block: 10.0.0.0/16
        region: "{{ AWS_REGION }}"
        tags:
          modules: ec2_vpc_net
          this:
        tenancy: default
        register: my_vpc

    - name: Cria Subnet
      ec2_vpc_subnet:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        state: present
        region: "{{ AWS_REGION }}"
        vpc_id: "{{ my_vpc.vpc.id }}"
        cidr: 10.0.1.0/24
        register: my_subnet

    - name: Cria Security Group
      ec2_group:
        name: "{{ SECURITY_GROUP }}"
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        description: regras de porta para o grupo
        vpc_id: "{{ my_vpc.vpc.id }}"
        region: "{{ AWS_REGION }}"
        rules:
         - proto: tcp
           ports:
           - 22
           - 80
           - 443
           cidr_ip: 0.0.0.0/0

    - name: Cria VM
      ec2_instance:
        key_name: "{{ APP_KEY }}"
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        instance_type: t2.micro
        image_id: ami-02b043c85d94864a9
        security_group: "{{ SECURITY_GROUP }}"
        tenancy: default
        name: "{{ VM_NAME }}"
        tags:
          Name: "{{ VM_NAME }}"
        wait: yes
        region: "{{ AWS_REGION }}"
        vpc_subnet_id: "{{ my_subnet.subnet.id }}"
        network:
          assign_public_ip: true