---

- name: Cria ec2 key 
  ec2_key:
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    name: "{{ APP_KEY }}"
    region: "{{ AWS_REGION }}"
  register: ec2_my_key

- name: Salva key ec2
  copy: content="{{ ec2_my_key.key.private_key }}" dest="../../../../{{ APP_KEY }}.pem" mode=0400
  when: ec2_my_key.changed

- name: Cria VPC
  ec2_vpc_net:
    name: "{{ VPC_NAME }}"
    cidr_block: "{{ VPC_CIDR }}"
    region: "{{ AWS_REGION }}"
    state: present
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
  register: vpc

- name: Subnet para o VPC
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ AWS_REGION }}"
    cidr: "{{ SUBNET_CIDR }}"
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    map_public: yes
    resource_tags:
      Name: "{{ SUBNET_NAME }}"
    register: subnet

- name: Cria IGW
  ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ AWS_REGION }}"
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    state:  present
    tags:
      Name: "{{ IGW_NAME }}"
    register: igw

- name: Rota IGW
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ AWS_REGION }}"
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    subnets:
     - "{{ subnet.subnet.id }}"
    routes:
     - dest: 0.0.0.0/0
       gateway_id: "{{ igw.gateway_id }}"
    tags:
      Name: "{{ ROUTE_NAME }}"

- name: Cria Security group
  ec2_group:
    name: "{{ SECURITY_GROUP }}"
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    description: fw
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ AWS_REGION }}"
    rules:
      - proto: tcp
        ports:
        - 22
        - 80
        - 443
        - 8080
        - 5000
        - 50000
        cidr_ip: 0.0.0.0/0

- name: Cria vm
  ec2_instance:
    key_name: "{{ APP_KEY }}"
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    instance_type: t2.micro
    image_id: ami-02b043c85d94864a9
    security_group: "{{ SECURITY_GROUP }}"
    tenancy: default
    name: "{{ VM_NAME }}"
    tags:
      Name: "{{ VM_NAME }}"
    wait: yes
    region: "{{ AWS_REGION }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    network:
      assign_public_ip: true

- name: Adiciona Ipv4 hosts
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: ci
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: ../../../../ssh_key_aws.pem